/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyStatus = IDL.Variant({
  'sold' : IDL.Null,
  'available' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'villa' : IDL.Null,
  'plot' : IDL.Null,
  'apartment' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : PropertyStatus,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageIds' : IDL.Vec(ExternalBlob),
  'areaSqFt' : IDL.Nat,
  'sellerId' : IDL.Principal,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'propertyId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'receiverId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProperty' : IDL.Func([Property], [IDL.Nat], []),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'filterProperties' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(PropertyType),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getPropertiesByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByType' : IDL.Func(
      [PropertyType],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getUserConversations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Principal, IDL.Principal))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Text], [IDL.Nat], []),
  'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyStatus = IDL.Variant({
    'sold' : IDL.Null,
    'available' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'villa' : IDL.Null,
    'plot' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : PropertyStatus,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageIds' : IDL.Vec(ExternalBlob),
    'areaSqFt' : IDL.Nat,
    'sellerId' : IDL.Principal,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'propertyId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'receiverId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProperty' : IDL.Func([Property], [IDL.Nat], []),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'filterProperties' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(PropertyType),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPropertiesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByType' : IDL.Func(
        [PropertyType],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getUserConversations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Principal, IDL.Principal))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Text], [IDL.Nat], []),
    'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
  });
};

export const init = ({ IDL }) => { return []; };