/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : bigint,
  'content' : string,
  'propertyId' : bigint,
  'isRead' : boolean,
  'receiverId' : Principal,
  'timestamp' : bigint,
  'senderId' : Principal,
}
export interface Property {
  'id' : bigint,
  'status' : PropertyStatus,
  'title' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'imageIds' : Array<ExternalBlob>,
  'areaSqFt' : bigint,
  'sellerId' : Principal,
  'bathrooms' : bigint,
  'price' : bigint,
  'location' : string,
}
export type PropertyStatus = { 'sold' : null } |
  { 'available' : null };
export type PropertyType = { 'commercial' : null } |
  { 'villa' : null } |
  { 'plot' : null } |
  { 'apartment' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProperty' : ActorMethod<[Property], bigint>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'filterProperties' : ActorMethod<
    [[] | [string], [] | [PropertyType], [] | [bigint], [] | [bigint]],
    Array<Property>
  >,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[bigint, Principal], Array<Message>>,
  'getPropertiesByLocation' : ActorMethod<[string], Array<Property>>,
  'getPropertiesBySeller' : ActorMethod<[Principal], Array<Property>>,
  'getPropertiesByType' : ActorMethod<[PropertyType], Array<Property>>,
  'getUserConversations' : ActorMethod<
    [],
    Array<[bigint, Principal, Principal]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, Principal, string], bigint>,
  'updateProperty' : ActorMethod<[bigint, Property], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];